name: secrets reveal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        env:
          SECRETS : ${{ secrets.SECRETS }}
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.SECRETS }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.SECRETS}} | sed 's/./& /g'
          echo env.SECRETS
